---
name: lint

"on": [push]

permissions:
  contents: read

jobs:
  lint:
    runs-on: [ubuntu-latest]

    env:
      SKIP_VENV: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Fetch main (for incremental diff, lint filter mask)
        run: git fetch origin main

      - name: Reload Cache / pip
        uses: actions/setup-python@v5
        with:
          python-version: 3
          cache: "pip" # caching pip dependencies
          cache-dependency-path: "**/requirements*.txt"
          update-environment: false

      - name: Install requirements
        run: make deps

      - name: Lint
        run: make lint
